### ISSUE TITLE
[Env registry] Enable Configuration service provider choice

### ISSUE THREAD

**Issue by dmitriyslaym** [capsulajs/capsulajs#19] opened 2019-04-17 07:20 UTC
## General description
Environment registry should give the ability to choose the configuration service provider which it works with. For now, the `LocalStorageProvider` is hard coded.

#### Design description

The `EnvRegistry` should expose as many variations as there are `ConfigurationService` providers.

- [x] Is it backward compatible ?
- [x] Adds new API
- [ ] Changes existing API
- [ ] Removes existing API

#### Changes
Current:
```typescript
export { EnvRegistry } from './EnvRegistry';
```

Future:
```typescript
export const EnvRegistryHardcoreRemote = getEnvRegistry(ConfigurationServiceHardcoreRemote);
export const EnvRegistryLocalStorage = getEnvRegistry(ConfigurationServiceLocalStorage);
export const EnvRegistryFile = getEnvRegistry(ConfigurationServiceFile);
export const EnvRegistryHttp = getEnvRegistry(ConfigurationServiceHttp);
```

#### Consideration
```gherkin
Given An EnvRegistry library
When I import EnvRegistryFile
Then I expect to use ConfigurationServiceFile
```

## Test cases

Link to the PR with test cases, that are written in _**[Gherkin Syntax](https://docs.cucumber.io/gherkin/reference/)**_ and cover all the possible scenarios.

## Ready for implementation
- [x] External dependencies have been resolved
- [x] API has been approved
- [ ] Test cases have been prepared
- [ ] Discussed with Product owner
- [ ] Discussed with Technical lead

**Comment by stephanebenayoun** [comment] 2019-06-02 08:23
Not relevant in this format. Duplicate of https://github.com/capsulajs/environment-registry/issues/17

**Closed by stephanebenayoun** 2019-06-02 08:23 UTC
